# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-12 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'user_details_hack17',
            },
        ),
        migrations.CreateModel(
            name='User_Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('device_id', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'db_table': 'user_devices_hack17',
            },
        ),
        migrations.CreateModel(
            name='User_Requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('requirements', jsonfield.fields.JSONField()),
                ('requirement_id', models.IntegerField()),
            ],
            options={
                'db_table': 'user_requirements_hack17',
            },
        ),
    ]
