"""
Django settings for domain_specific_language project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@7)l504%1ez%2o7z)ciq&k%jyvf%wqvy*+2s_u3wkpuemx(=wt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'broker_to_customer',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'domain_specific_language.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'domain_specific_language.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'mydb',
        'USER': 'mydb',
        'PASSWORD': 'mydb',
        'HOST': '10.1.6.46',
        'PORT': '5432',
        'CONN_MAX_AGE': 300,
        'OPTIONS': {
            'options': '-c search_path=public,postgis'
        }
    },
    # 'default': {
    #     'ENGINE': 'django.contrib.gis.db.backends.postgis',
    #     'NAME': 'housing_analytics',
    #     'USER': 'dsl_readonly',
    #     'PASSWORD': 'dsl',
    #     'HOST': '127.0.0.1',
    #     'PORT': '5434',
    #     'OPTIONS': {
    #         'options': '-c search_path=public,postgis'
    #     }
    # },
    'housing_analytics': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'housing_analytics',
        'USER': 'dsl_readonly',
        'PASSWORD': 'dsl',
        'HOST': '127.0.0.1',
        'PORT': '5434',
        'OPTIONS': {
            'options': '-c search_path=public,postgis'
        }
    },
    'housing_regions_production': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'housing_regions_production',
        'USER': 'housing_su',
        'PASSWORD': 'housing',
        'HOST': 'manishu.housing.com',
        'PORT': '5432',
        'OPTIONS': {
            'options': '-c search_path=public,postgis'
        }
    },
    'housing_production': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'housing_production',
        'USER': 'housing',
        'PASSWORD': 'housing',
        'HOST': 'manishu.housing.com',
        'PORT': '5432',
        'OPTIONS': {
            'options': '-c search_path=public,postgis'
        }
    },
    'housing_pg_production': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'housing_pg_production',
        'USER': 'housing',
        'PASSWORD': 'housing',
        'HOST': '127.0.0.1',
        'PORT': '5433'
    },
    'housing_np_production': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'housing_np_production',
        'USER': 'housing_su',
        'PASSWORD': 'housing',
        'HOST': 'manishu.housing.com',
        'PORT': '5432',
        'OPTIONS': {
            'options': '-c search_path=public,postgis'
        }
    },
    'housing_subscription_production': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'housing_subscription_production',
        'USER': 'housing',
        'PASSWORD': 'housing',
        'HOST': '127.0.0.1',
        'PORT': '5433'
    },
    'email_service_production': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'email_service_production',
        'USER': 'housing',
        'PASSWORD': 'housing',
        'HOST': '127.0.0.1',
        'PORT': '5433'
    },
    'housing_clients_production': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'housing_clients_production',
        'USER': 'housing_su',
        'PASSWORD': 'housing',
        'HOST': 'manishu.housing.com',
        'PORT': '5432'
    },
    'housing_leads_production': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'housing_leads_production',
        'USER': 'housing_su',
        'PASSWORD': 'housing',
        'HOST': 'manishu.housing.com',
        'PORT': '5432'
    }
}



# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
RABBITMQ_URI = 'amqp://guest:guest@10.1.6.46:5672/%2F?socket_timeout:10'
